In [21]:
import pandas as pd
import os

In [22]:
train_test_data = pd.read_csv(os.path.join('..','data','Landslide_Data.csv'))
point_data = pd.read_csv(os.path.join('..','data','Point_data.csv'))

In [23]:
train_test_data.head(5)

,OBJECTID,Landslide,Aspect,Curvature,Elevation,Geology,LULC_2020,NDVI,Road_dist,Slope,SoilTexture,SoilType,SPI,Stream_dist
0,1,1,190.491470,-0.222222,36,7,2,0.263359,381.837677,19.304520,21,4,-0.370848,67.082039
1,2,1,205.709961,0.666667,43,7,2,0.286868,366.196655,19.526470,21,4,0.409195,67.082039
2,3,1,236.040939,0.333333,89,7,2,0.291367,540.832703,12.309163,3,1,-1.394833,240.000000
3,4,1,187.943466,0.444444,106,7,2,0.361999,600.000000,20.940453,3,1,-0.318317,283.019440
4,5,1,230.262390,0.111111,160,7,2,0.309558,816.088257,24.932274,3,1,-0.101314,284.604981

In [24]:
train_test_data.columns

Index(['OBJECTID', 'Landslide', 'Aspect', 'Curvature', 'Elevation', 'Geology',
       'LULC_2020', 'NDVI', 'Road_dist', 'Slope', 'SoilTexture', 'SoilType',
       'SPI', 'Stream_dist'],
      dtype='object')

In [25]:
point_data.head(5)

,OBJECTID,pointid,Elevation,Aspect,Curvature,Geology,LULC_2020,NDVI,Road_dist,Slope,SoilTexture,SoilType,SPI,Stream_dist
0,1,1,75.0,302.195740,0.222222,3,2,0.289782,3062.352051,7.726209,3,1,-8.915490,591.692505
1,2,2,78.0,322.125031,0.555556,3,2,0.297374,3037.712891,5.779747,3,1,-9.248405,566.038879
2,3,3,77.0,36.253838,-0.222222,3,2,0.302728,3013.171143,4.122546,3,1,-9.449757,540.832703
3,4,4,74.0,79.824486,-0.000000,3,2,0.331275,2988.728760,8.085025,4,1,-1.098921,516.139526
4,5,5,52.0,40.364536,0.777778,3,2,0.327888,1958.979370,11.215478,4,1,-8.420445,120.000000

In [26]:
for col in ['Geology', 'LULC_2020',  'SoilTexture', 'SoilType']:
    train_test_data[col] = train_test_data[col].astype('category')
    point_data[col] = point_data[col].astype('category')

In [27]:
print('In train test data:\n')
for col in ['Geology', 'LULC_2020',  'SoilTexture', 'SoilType']:
    print('Unique categories for '+col)
    print(list(train_test_data[col].unique()))
    print('\n')

In train test data:

Unique categories for Geology
[7, 2, 5, 12, 6, 9, 11, 1, 4, 3, 10]


Unique categories for LULC_2020
[2, 0, 4, 3]


Unique categories for SoilTexture
[21, 3, 10, 16, 20, 2, 4, 7, 5, 6, 1, 13, 8, 17, 18, 12, 19]


Unique categories for SoilType
[4, 1, 2, 6, 5]

In [28]:
print('In point data:\n')
for col in ['Geology', 'LULC_2020',  'SoilTexture', 'SoilType']:
    print('Unique categories for '+col)
    print(list(point_data[col].unique()))
    print('\n')

In point data:

Unique categories for Geology
[3, 6, 9, 4, 7, 1, 10, 11, 5, 12, 2]


Unique categories for LULC_2020
[2, 4, 3, 0]


Unique categories for SoilTexture
[3, 4, 6, 2, 7, 1, 5, 8, 11, 10, 13, 15, 17, 14, 18, 16, 12, 19, 20, 21]


Unique categories for SoilType
[1, 6, 2, 4, 3, 5]

In [29]:
print('Missing categories (which are presesnt in point data but not in train test data):\n')
for col in ['Geology', 'LULC_2020',  'SoilTexture', 'SoilType']:
    print('Missing categories for '+col)
    ttd=list(train_test_data[col].unique())
    pd=list(point_data[col].unique())
    m = list(set(pd) - set(ttd))
    print(m)
    print('\n')

Missing categories (which are presesnt in point data but not in train test data):

Missing categories for Geology
[]


Missing categories for LULC_2020
[]


Missing categories for SoilTexture
[11, 14, 15]


Missing categories for SoilType
[3]